ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "strategy" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "marketPriceM2" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "dpe" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "transport" TEXT;
